---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kiaboluk/public_html/cngtest
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R app       $DEPLOYPATH
    - /bin/cp -R database  $DEPLOYPATH
    - /bin/cp -R public    $DEPLOYPATH
    - /bin/cp -R routes    $DEPLOYPATH
    - /bin/cp -R storage   $DEPLOYPATH
    - /bin/cp -R uploads   $DEPLOYPATH